name: 'coverage'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
    coverage:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./website
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
